// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"
)

// Defines values for ErrorBodyCode.
const (
	ExecNotFound       ErrorBodyCode = "exec_not_found"
	InternalError      ErrorBodyCode = "internal_error"
	InvalidRequest     ErrorBodyCode = "invalid_request"
	InvalidState       ErrorBodyCode = "invalid_state"
	NameTaken          ErrorBodyCode = "name_taken"
	ResourceExhausted  ErrorBodyCode = "resource_exhausted"
	RuntimeUnavailable ErrorBodyCode = "runtime_unavailable"
	SandboxNotFound    ErrorBodyCode = "sandbox_not_found"
	Unauthorized       ErrorBodyCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorBodyCode enum.
func (e ErrorBodyCode) Valid() bool {
	switch e {
	case ExecNotFound:
		return true
	case InternalError:
		return true
	case InvalidRequest:
		return true
	case InvalidState:
		return true
	case NameTaken:
		return true
	case ResourceExhausted:
		return true
	case RuntimeUnavailable:
		return true
	case SandboxNotFound:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for ExecState.
const (
	ExecStateExited  ExecState = "exited"
	ExecStateFailed  ExecState = "failed"
	ExecStateRunning ExecState = "running"
)

// Valid indicates whether the value is a known member of the ExecState enum.
func (e ExecState) Valid() bool {
	switch e {
	case ExecStateExited:
		return true
	case ExecStateFailed:
		return true
	case ExecStateRunning:
		return true
	default:
		return false
	}
}

// Defines values for SandboxState.
const (
	SandboxStateCreating   SandboxState = "creating"
	SandboxStateDestroyed  SandboxState = "destroyed"
	SandboxStateDestroying SandboxState = "destroying"
	SandboxStateError      SandboxState = "error"
	SandboxStateRunning    SandboxState = "running"
	SandboxStateStopped    SandboxState = "stopped"
)

// Valid indicates whether the value is a known member of the SandboxState enum.
func (e SandboxState) Valid() bool {
	switch e {
	case SandboxStateCreating:
		return true
	case SandboxStateDestroyed:
		return true
	case SandboxStateDestroying:
		return true
	case SandboxStateError:
		return true
	case SandboxStateRunning:
		return true
	case SandboxStateStopped:
		return true
	default:
		return false
	}
}

// CreateExecRequest defines model for CreateExecRequest.
type CreateExecRequest struct {
	Command    []string           `json:"command"`
	Env        *map[string]string `json:"env,omitempty"`
	User       *string            `json:"user,omitempty"`
	WorkingDir *string            `json:"working_dir,omitempty"`
}

// CreateSandboxRequest defines model for CreateSandboxRequest.
type CreateSandboxRequest struct {
	CpuMillis   *int               `json:"cpu_millis,omitempty"`
	Env         *map[string]string `json:"env,omitempty"`
	Image       string             `json:"image"`
	Labels      *map[string]string `json:"labels,omitempty"`
	MemoryBytes *int64             `json:"memory_bytes,omitempty"`
	Name        *string            `json:"name,omitempty"`
	PidsLimit   *int               `json:"pids_limit,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    ErrorBodyCode           `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorBodyCode defines model for ErrorBody.Code.
type ErrorBodyCode string

// Exec defines model for Exec.
type Exec struct {
	Command     []string           `json:"command"`
	Env         *map[string]string `json:"env,omitempty"`
	ExitCode    *int               `json:"exit_code,omitempty"`
	FinishedAt  *time.Time         `json:"finished_at,omitempty"`
	Id          string             `json:"id"`
	OutputBytes int64              `json:"output_bytes"`
	SandboxId   string             `json:"sandbox_id"`
	StartedAt   time.Time          `json:"started_at"`
	State       ExecState          `json:"state"`
	Truncated   bool               `json:"truncated"`
	User        *string            `json:"user,omitempty"`
	WorkingDir  *string            `json:"working_dir,omitempty"`
}

// ExecState defines model for Exec.State.
type ExecState string

// ExecList defines model for ExecList.
type ExecList struct {
	Items      []Exec  `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Resources defines model for Resources.
type Resources struct {
	CpuMillis   int   `json:"cpu_millis"`
	MemoryBytes int64 `json:"memory_bytes"`
	PidsLimit   int   `json:"pids_limit"`
}

// Sandbox defines model for Sandbox.
type Sandbox struct {
	CreatedAt time.Time          `json:"created_at"`
	Env       *map[string]string `json:"env,omitempty"`
	Id        string             `json:"id"`
	Image     string             `json:"image"`
	Labels    *map[string]string `json:"labels,omitempty"`
	Name      *string            `json:"name,omitempty"`
	Resources Resources          `json:"resources"`
	Runtime   string             `json:"runtime"`
	State     SandboxState       `json:"state"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// SandboxState defines model for Sandbox.State.
type SandboxState string

// SandboxList defines model for SandboxList.
type SandboxList struct {
	Items      []Sandbox `json:"items"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// Version defines model for Version.
type Version struct {
	ApiVersions []string `json:"api_versions"`
	Version     string   `json:"version"`
}

// GetExecOutputParams defines parameters for GetExecOutput.
type GetExecOutputParams struct {
	From *int64 `form:"from,omitempty" json:"from,omitempty"`
}

// ListSandboxesParams defines parameters for ListSandboxes.
type ListSandboxesParams struct {
	Limit  *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string   `form:"cursor,omitempty" json:"cursor,omitempty"`
	State  *string   `form:"state,omitempty" json:"state,omitempty"`
	Label  *[]string `form:"label,omitempty" json:"label,omitempty"`
}

// ListExecsParams defines parameters for ListExecs.
type ListExecsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateSandboxJSONRequestBody defines body for CreateSandbox for application/json ContentType.
type CreateSandboxJSONRequestBody = CreateSandboxRequest

// CreateExecJSONRequestBody defines body for CreateExec for application/json ContentType.
type CreateExecJSONRequestBody = CreateExecRequest
