// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"
)

// Defines values for ErrorBodyCode.
const (
	ExecNotFound       ErrorBodyCode = "exec_not_found"
	Forbidden          ErrorBodyCode = "forbidden"
	InternalError      ErrorBodyCode = "internal_error"
	InvalidRequest     ErrorBodyCode = "invalid_request"
	InvalidState       ErrorBodyCode = "invalid_state"
	NameTaken          ErrorBodyCode = "name_taken"
	PathNotFound       ErrorBodyCode = "path_not_found"
	ResourceExhausted  ErrorBodyCode = "resource_exhausted"
	RuntimeUnavailable ErrorBodyCode = "runtime_unavailable"
	SandboxNotFound    ErrorBodyCode = "sandbox_not_found"
	SnapshotNotFound   ErrorBodyCode = "snapshot_not_found"
	TokenNotFound      ErrorBodyCode = "token_not_found"
	Unauthorized       ErrorBodyCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorBodyCode enum.
func (e ErrorBodyCode) Valid() bool {
	switch e {
	case ExecNotFound:
		return true
	case Forbidden:
		return true
	case InternalError:
		return true
	case InvalidRequest:
		return true
	case InvalidState:
		return true
	case NameTaken:
		return true
	case PathNotFound:
		return true
	case ResourceExhausted:
		return true
	case RuntimeUnavailable:
		return true
	case SandboxNotFound:
		return true
	case SnapshotNotFound:
		return true
	case TokenNotFound:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for ExecState.
const (
	ExecStateExited  ExecState = "exited"
	ExecStateFailed  ExecState = "failed"
	ExecStateRunning ExecState = "running"
)

// Valid indicates whether the value is a known member of the ExecState enum.
func (e ExecState) Valid() bool {
	switch e {
	case ExecStateExited:
		return true
	case ExecStateFailed:
		return true
	case ExecStateRunning:
		return true
	default:
		return false
	}
}

// Defines values for SandboxState.
const (
	SandboxStateCreating   SandboxState = "creating"
	SandboxStateDestroyed  SandboxState = "destroyed"
	SandboxStateDestroying SandboxState = "destroying"
	SandboxStateError      SandboxState = "error"
	SandboxStateRunning    SandboxState = "running"
	SandboxStateStopped    SandboxState = "stopped"
)

// Valid indicates whether the value is a known member of the SandboxState enum.
func (e SandboxState) Valid() bool {
	switch e {
	case SandboxStateCreating:
		return true
	case SandboxStateDestroyed:
		return true
	case SandboxStateDestroying:
		return true
	case SandboxStateError:
		return true
	case SandboxStateRunning:
		return true
	case SandboxStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for Scope.
const (
	ScopeAdmin          Scope = "admin"
	ScopeAsterisk       Scope = "*"
	ScopeAuditRead      Scope = "audit:read"
	ScopeExec           Scope = "exec"
	ScopeFilesRead      Scope = "files:read"
	ScopeFilesWrite     Scope = "files:write"
	ScopeSandboxesRead  Scope = "sandboxes:read"
	ScopeSandboxesWrite Scope = "sandboxes:write"
	ScopeSnapshotsRead  Scope = "snapshots:read"
	ScopeSnapshotsWrite Scope = "snapshots:write"
)

// Valid indicates whether the value is a known member of the Scope enum.
func (e Scope) Valid() bool {
	switch e {
	case ScopeAdmin:
		return true
	case ScopeAsterisk:
		return true
	case ScopeAuditRead:
		return true
	case ScopeExec:
		return true
	case ScopeFilesRead:
		return true
	case ScopeFilesWrite:
		return true
	case ScopeSandboxesRead:
		return true
	case ScopeSandboxesWrite:
		return true
	case ScopeSnapshotsRead:
		return true
	case ScopeSnapshotsWrite:
		return true
	default:
		return false
	}
}

// CreateExecRequest defines model for CreateExecRequest.
type CreateExecRequest struct {
	Command    []string           `json:"command"`
	Env        *map[string]string `json:"env,omitempty"`
	User       *string            `json:"user,omitempty"`
	WorkingDir *string            `json:"working_dir,omitempty"`
}

// CreateSandboxRequest Exactly one of image or snapshot must be supplied
type CreateSandboxRequest struct {
	CpuMillis   *int               `json:"cpu_millis,omitempty"`
	Env         *map[string]string `json:"env,omitempty"`
	Image       *string            `json:"image,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`
	MemoryBytes *int64             `json:"memory_bytes,omitempty"`
	Name        *string            `json:"name,omitempty"`
	PidsLimit   *int               `json:"pids_limit,omitempty"`
	Snapshot    *string            `json:"snapshot,omitempty"`
}

// CreateSnapshotRequest defines model for CreateSnapshotRequest.
type CreateSnapshotRequest struct {
	Name *string `json:"name,omitempty"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	ExpiresInSeconds *int64  `json:"expires_in_seconds,omitempty"`
	Name             string  `json:"name"`
	Scopes           []Scope `json:"scopes"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	Id         string     `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	RevokedAt  *time.Time `json:"revoked_at,omitempty"`
	Scopes     []Scope    `json:"scopes"`

	// Token The plaintext, returned only here and never again
	Token string `json:"token"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    ErrorBodyCode           `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorBodyCode defines model for ErrorBody.Code.
type ErrorBodyCode string

// Exec defines model for Exec.
type Exec struct {
	Command     []string           `json:"command"`
	Env         *map[string]string `json:"env,omitempty"`
	ExitCode    *int               `json:"exit_code,omitempty"`
	FinishedAt  *time.Time         `json:"finished_at,omitempty"`
	Id          string             `json:"id"`
	OutputBytes int64              `json:"output_bytes"`
	SandboxId   string             `json:"sandbox_id"`
	StartedAt   time.Time          `json:"started_at"`
	State       ExecState          `json:"state"`
	Truncated   bool               `json:"truncated"`
	User        *string            `json:"user,omitempty"`
	WorkingDir  *string            `json:"working_dir,omitempty"`
}

// ExecState defines model for Exec.State.
type ExecState string

// ExecList defines model for ExecList.
type ExecList struct {
	Items      []Exec  `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// FileInfo defines model for FileInfo.
type FileInfo struct {
	IsDir      bool    `json:"is_dir"`
	LinkTarget *string `json:"link_target,omitempty"`

	// Mode Octal permission string, e.g. 0644
	Mode  string    `json:"mode"`
	Mtime time.Time `json:"mtime"`
	Name  string    `json:"name"`
	Size  int64     `json:"size"`
}

// FileList defines model for FileList.
type FileList struct {
	Items []FileInfo `json:"items"`

	// Truncated True when the listing hit a configured cap and is incomplete
	Truncated bool `json:"truncated"`
}

// Resources defines model for Resources.
type Resources struct {
	CpuMillis   int   `json:"cpu_millis"`
	MemoryBytes int64 `json:"memory_bytes"`
	PidsLimit   int   `json:"pids_limit"`
}

// RestoreRequest defines model for RestoreRequest.
type RestoreRequest struct {
	Snapshot string `json:"snapshot"`
}

// Sandbox defines model for Sandbox.
type Sandbox struct {
	CreatedAt        time.Time          `json:"created_at"`
	Env              *map[string]string `json:"env,omitempty"`
	Id               string             `json:"id"`
	Image            string             `json:"image"`
	Labels           *map[string]string `json:"labels,omitempty"`
	Name             *string            `json:"name,omitempty"`
	ParentSnapshotId *string            `json:"parent_snapshot_id,omitempty"`
	Resources        Resources          `json:"resources"`
	Runtime          string             `json:"runtime"`
	State            SandboxState       `json:"state"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

// SandboxState defines model for Sandbox.State.
type SandboxState string

// SandboxList defines model for SandboxList.
type SandboxList struct {
	Items      []Sandbox `json:"items"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// Scope defines model for Scope.
type Scope string

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CreatedAt  time.Time `json:"created_at"`
	Id         string    `json:"id"`
	Image      string    `json:"image"`
	Name       *string   `json:"name,omitempty"`
	ParentId   *string   `json:"parent_id,omitempty"`
	RuntimeRef string    `json:"runtime_ref"`
	SandboxId  string    `json:"sandbox_id"`

	// SizeBytes Apparent image size including shared layers, not incremental disk use
	SizeBytes int64 `json:"size_bytes"`
}

// SnapshotList defines model for SnapshotList.
type SnapshotList struct {
	Items      []Snapshot `json:"items"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// Token defines model for Token.
type Token struct {
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	Id         string     `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	RevokedAt  *time.Time `json:"revoked_at,omitempty"`
	Scopes     []Scope    `json:"scopes"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Items []Token `json:"items"`
}

// Version defines model for Version.
type Version struct {
	ApiVersions []string `json:"api_versions"`
	Version     string   `json:"version"`
}

// GetExecOutputParams defines parameters for GetExecOutput.
type GetExecOutputParams struct {
	From *int64 `form:"from,omitempty" json:"from,omitempty"`
}

// ListSandboxesParams defines parameters for ListSandboxes.
type ListSandboxesParams struct {
	Limit  *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string   `form:"cursor,omitempty" json:"cursor,omitempty"`
	State  *string   `form:"state,omitempty" json:"state,omitempty"`
	Label  *[]string `form:"label,omitempty" json:"label,omitempty"`
}

// GetArchiveParams defines parameters for GetArchive.
type GetArchiveParams struct {
	Path string `form:"path" json:"path"`
}

// PutArchiveParams defines parameters for PutArchive.
type PutArchiveParams struct {
	Path string `form:"path" json:"path"`
}

// ListExecsParams defines parameters for ListExecs.
type ListExecsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	Path string `form:"path" json:"path"`
}

// PutFileParams defines parameters for PutFile.
type PutFileParams struct {
	Path string `form:"path" json:"path"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	Path string `form:"path" json:"path"`
}

// StatFileParams defines parameters for StatFile.
type StatFileParams struct {
	Path string `form:"path" json:"path"`
}

// ListSandboxSnapshotsParams defines parameters for ListSandboxSnapshots.
type ListSandboxSnapshotsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSnapshotsParams defines parameters for ListSnapshots.
type ListSnapshotsParams struct {
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Sandbox *string `form:"sandbox,omitempty" json:"sandbox,omitempty"`
}

// CreateSandboxJSONRequestBody defines body for CreateSandbox for application/json ContentType.
type CreateSandboxJSONRequestBody = CreateSandboxRequest

// CreateExecJSONRequestBody defines body for CreateExec for application/json ContentType.
type CreateExecJSONRequestBody = CreateExecRequest

// RestoreSandboxJSONRequestBody defines body for RestoreSandbox for application/json ContentType.
type RestoreSandboxJSONRequestBody = RestoreRequest

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody = CreateSnapshotRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest
