import type { components } from "./models.js";

export type Sandbox = components["schemas"]["Sandbox"];
export type SandboxList = components["schemas"]["SandboxList"];
export type CreateSandboxRequest = components["schemas"]["CreateSandboxRequest"];
export type Exec = components["schemas"]["Exec"];
export type ExecList = components["schemas"]["ExecList"];
export type Snapshot = components["schemas"]["Snapshot"];
export type SnapshotList = components["schemas"]["SnapshotList"];
export type Token = components["schemas"]["Token"];
export type TokenList = components["schemas"]["TokenList"];
export type CreatedToken = components["schemas"]["CreatedToken"];
export type CreateTokenRequest = components["schemas"]["CreateTokenRequest"];
export type Event = components["schemas"]["Event"];
export type EventList = components["schemas"]["EventList"];
export type FileInfo = components["schemas"]["FileInfo"];
export type FileList = components["schemas"]["FileList"];
export type ErrorBody = components["schemas"]["ErrorBody"];
export type Resources = components["schemas"]["Resources"];
export type Version = components["schemas"]["Version"];
export type Network = components["schemas"]["Network"];
export type Scope = components["schemas"]["Scope"];
