# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


@dataclass
class Version:
    version: str
    api_versions: list[str]


@dataclass
class Resources:
    cpu_millis: int
    memory_bytes: int
    pids_limit: int


class Network(Enum):
    full = 'full'
    none = 'none'


class State(Enum):
    creating = 'creating'
    running = 'running'
    stopped = 'stopped'
    destroying = 'destroying'
    destroyed = 'destroyed'
    error = 'error'


@dataclass
class Sandbox:
    id: str
    image: str
    state: State
    runtime: str
    resources: Resources
    network: Network
    created_at: str
    updated_at: str
    name: str | None = None
    oci_runtime: str | None = None
    env: dict[str, str] | None = None
    labels: dict[str, str] | None = None
    parent_snapshot_id: str | None = None


@dataclass
class SandboxList:
    items: list[Sandbox]
    next_cursor: str | None = None


@dataclass
class CreateSandboxRequest:
    name: str | None = None
    image: str | None = None
    snapshot: str | None = None
    cpu_millis: int | None = None
    memory_bytes: int | None = None
    pids_limit: int | None = None
    network: Network | None = None
    env: dict[str, str] | None = None
    labels: dict[str, str] | None = None


@dataclass
class CreateExecRequest:
    command: list[str]
    env: dict[str, str] | None = None
    working_dir: str | None = None
    user: str | None = None


class State1(Enum):
    running = 'running'
    exited = 'exited'
    failed = 'failed'


@dataclass
class Exec:
    id: str
    sandbox_id: str
    command: list[str]
    state: State1
    output_bytes: int
    truncated: bool
    started_at: str
    env: dict[str, str] | None = None
    working_dir: str | None = None
    user: str | None = None
    exit_code: int | None = None
    finished_at: str | None = None


@dataclass
class ExecList:
    items: list[Exec]
    next_cursor: str | None = None


@dataclass
class Snapshot:
    id: str
    sandbox_id: str
    runtime_ref: str
    image: str
    size_bytes: int
    created_at: str
    name: str | None = None
    parent_id: str | None = None
    network: Network | None = None


@dataclass
class SnapshotList:
    items: list[Snapshot]
    next_cursor: str | None = None


@dataclass
class CreateSnapshotRequest:
    name: str | None = None


@dataclass
class RestoreRequest:
    snapshot: str


@dataclass
class FileInfo:
    name: str
    size: int
    mode: str
    mtime: str
    is_dir: bool
    link_target: str | None = None


@dataclass
class FileList:
    items: list[FileInfo]
    truncated: bool


class Scope(Enum):
    sandboxes_read = 'sandboxes:read'
    sandboxes_write = 'sandboxes:write'
    exec = 'exec'
    files_read = 'files:read'
    files_write = 'files:write'
    snapshots_read = 'snapshots:read'
    snapshots_write = 'snapshots:write'
    audit_read = 'audit:read'
    admin = 'admin'
    field_ = '*'


@dataclass
class Token:
    id: str
    name: str
    prefix: str
    scopes: list[Scope]
    created_at: str
    expires_at: str | None = None
    last_used_at: str | None = None
    revoked_at: str | None = None


@dataclass
class TokenList:
    items: list[Token]


@dataclass
class CreateTokenRequest:
    name: str
    scopes: list[Scope]
    expires_in_seconds: int | None = None


@dataclass
class CreatedToken(Token):
    token: str = field(kw_only=True)


@dataclass
class Event:
    id: str
    ts: str
    action: str
    request_id: str
    status: int
    actor_token_id: str | None = None
    actor_name: str | None = None
    resource_type: str | None = None
    resource_id: str | None = None
    remote_addr: str | None = None
    details: dict[str, Any] | None = None


@dataclass
class EventList:
    items: list[Event]
    next_cursor: str | None = None


class Code(Enum):
    invalid_request = 'invalid_request'
    unauthorized = 'unauthorized'
    forbidden = 'forbidden'
    token_not_found = 'token_not_found'
    sandbox_not_found = 'sandbox_not_found'
    snapshot_not_found = 'snapshot_not_found'
    exec_not_found = 'exec_not_found'
    name_taken = 'name_taken'
    invalid_state = 'invalid_state'
    resource_exhausted = 'resource_exhausted'
    runtime_unavailable = 'runtime_unavailable'
    internal_error = 'internal_error'
    path_not_found = 'path_not_found'


@dataclass
class ErrorBody:
    code: Code
    message: str
    details: dict[str, Any] | None = None


@dataclass
class Error:
    error: ErrorBody
